---
abstract: 'Sinatra-ish framework on Amon2!'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Lite
no_index:
  directory:
    - inc
provides:
  Amon2::Lite:
    file: lib/Amon2/Lite.pm
    version: 0.06
  Amon2::Setup::Flavor::Lite:
    file: lib/Amon2/Setup/Flavor/Lite.pm
    version: 0.01
requires:
  Amon2: 3.25
  Data::Section::Simple: 0.03
  Router::Simple: 0.06
  Text::Xslate::Bridge::TT2Like: 0.00010
  perl: 5.008008
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
